name: Go CI/CD and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: DEV # Specify the environment to access the correct secrets

    services:
      grpc-server:
        image: grpc/go:1.39
        ports:
          - 50051:50051
        options: >-
          --health-cmd="grpc_health_probe -addr=localhost:50051"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Set up Firebase credentials
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > $HOME/firebase-creds.json

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build -v ./...

      - name: Run tests
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-creds.json
          GRPC_SERVER_ADDRESS: ${{ secrets.GRPC_SERVER_ADDRESS }}
        run: |
          go test -v ./...

      - name: Lint code
        run: golangci-lint run

      - name: Run gRPC connection tests
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-creds.json
          GRPC_SERVER_ADDRESS: ${{ secrets.GRPC_SERVER_ADDRESS }}
        run: |
          go test -v ./path/to/grpc_client_test.go  # Adjust this path to where your gRPC client tests are located

  # deploy:
  #   needs: build-and-test
  #   runs-on: ubuntu-latest
  #   environment: DEV # Specify the environment to access the correct secrets

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Set up Firebase credentials
  #       run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > $HOME/firebase-creds.json

  #     - name: Install Firebase CLI
  #       run: curl -sL https://firebase.tools | bash

  #     - name: Deploy to Firebase
  #       env:
  #         FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  #       run: |
  #         firebase deploy --only hosting
