name: TravelGo CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: DEV # Specify the DEV environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Set up Firebase credentials
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > $HOME/firebase-creds.json

      - name: Install dependencies
        run: go mod tidy

      - name: Set gRPC server URL
        run: echo "GRPC_SERVER_URL=${{ secrets.GRPC_SERVER_URL }}" >> $GITHUB_ENV

      - name: Build the service
        run: go build -v -o travelgo .

      - name: Run tests
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-creds.json
          GRPC_SERVER_URL: ${{ secrets.GRPC_SERVER_URL }}
        run: go test -v ./...

      - name: Lint code
        run: golangci-lint run

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Google Container Registry
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64 -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/travelgo:latest --push .

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: DEV # Specify the DEV environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Firebase credentials
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > $HOME/firebase-creds.json

      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Deploy to Google Cloud Run
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-creds.json
        run: |
          gcloud run deploy travelgo \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/travelgo:latest \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --port 8080 \
            --allow-unauthenticated
